apiVersion: v1
kind: ConfigMap
metadata:
  name: visbo-rest-config
  namespace: visbo
data:
  SERVER_PORT: "3484"
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  REDIS_HOST: "redis.visbo.svc.cluster.local"
  REDIS_PORT: "6379"
