apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: visbo
resources:
  - namespace.yaml
  - configmap-visbo-rest.yaml
  - secret-visbo-rest.yaml
  - deployment-visbo-rest.yaml
  - service-visbo-rest.yaml
  - ingress-visbo-rest.yaml
